print("Ingrese la cantidad de dinero que va a depositar en la cuenta de ahorro")
deposito =float(input())
primeranno = deposito * (1 + 0.04)
segundoanno = primeranno * (1 + 0.04)
terceranno = segundoanno * (1 + 0.04)
primeranno = round(primeranno,2)
segundoanno = round(segundoanno,2)
terceranno = round(terceranno,2)
print(F"la cantidad de ahorros despues del primer anno es de {primeranno}, del segundo es de {segundoanno} y de tercero es de {terceranno}")